### ISSUE TITLE
Missing protocol

### ISSUE THREAD

**Issue by misitoth** [latysheff/node-sctp#1]
Hi,

Can you define LCSAP protocol in lib/defs.js payload_protocol_identifier?
LCSAP identifier 29 according to [iana](https://www.iana.org/assignments/sctp-parameters/sctp-parameters.xhtml#sctp-parameters-25) SCTP Payload Protocol Identifiers.

Thanks

**Comment by latysheff** [comment]
Hi, never thought someone will need this :)
OK, in next update I will add all know protocols. Meanwhile, just use integer 29.

**Comment by misitoth** [comment]
Hi,

If you can add all know protocol, there is not gonna be problem in the future. I want to use your package in my test environment with E-SMLC, that is the reason why I desperately need this protocol :-)

Thanks anyway.

**Comment by latysheff** [comment]
Hey, there's no problem at all, because:
1) SCTP RFC doesn't require setting any protocol identifier (default zero should be OK)
2) you can set it like this (API may change):
socket.setWriteOptions({protocol:29});

By the way, are you going to implement LCS-AP on top node-sctp?

**Comment by misitoth** [comment]
Hi,

I will use your option2, I hope documentation will be extended with more examples.
I am planning LCS-AP in my environment, when sctp layer establish association properly.

**Comment by latysheff** [comment]
Do you have problems with establishing connection?

**Comment by latysheff** [comment]
resolved in new version
