### ISSUE TITLE
Release 1.0.0 to avoid `npm i` issues

### ISSUE THREAD

**Issue by ibc** [latysheff/node-sctp#20]
When version is `0.X.Y`, running `npm install sctp` rewrites `package.json` as follows:

```
"sctp": "0.0.21",
```

Even if you add `^` to allow auto-upgrades with same mayor version, `npm install whatever` will remove the `^`. This is, apps/libs depending on sctp `0.0.20` will not get version `0.0.21` when running `npm install` and will always install sctp `0.0.20`.

This seems to be `npm` policy. Releasing a `1.0.0` version would avoid this issue.

**Comment by latysheff** [comment]
done
